version: '3.3'
services:
  springboot:
    container_name: transactionAPI
    build:
      dockerfile: Dockerfile
    image: transactionapi:latest
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: transactiondb
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: 'transactiondb'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
